## Dataset

In [1]:
import os,sys
sys.path.append("../src")
from Datasets import DatasetSSL
from utils.hparams import HParam
hp = HParam("../config/v0.yaml","../config/default.yaml")

/home/kbh/.conda/envs/dnn/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
dataset = DatasetSSL(hp)
print(len(dataset))

4876


In [3]:
feature,label = dataset[0]

logdb : (1, 257, 139)
R : (2, 257, 139)
logdb : (1, 257, 139)


In [4]:
feature.shape

torch.Size([4, 139, 257])

## Pred

In [5]:
import torch

In [10]:
x = torch.rand(2,3,4)
print(x)

scores = x.mean(1)
print(scores)
print(scores.shape)
best_prediction = scores.max(-1)[1]
print(best_prediction)
print(best_prediction.shape)

tensor([[[0.6819, 0.2661, 0.8686, 0.7532],
         [0.6004, 0.8246, 0.5651, 0.4807],
         [0.7912, 0.9077, 0.3623, 0.7677]],

        [[0.3681, 0.7407, 0.6906, 0.7858],
         [0.6747, 0.0022, 0.8579, 0.6381],
         [0.2831, 0.9368, 0.9458, 0.5069]]])
tensor([[0.6912, 0.6662, 0.5987, 0.6672],
        [0.4420, 0.5599, 0.8314, 0.6436]])
torch.Size([2, 4])
tensor([0, 2])
torch.Size([2])
